list1 = ["Ibrahim",'Abdul','''Sattar''',True,False,3.14,4,]
print(list1)
print(type(list1))

for item in list1:
    print(item," ",end="")
    print(type(item))

print("\nLength of list1 is: ",len(list1))
print("list1[0]: ",list1[0])
print("list1[1]: ",list1[1])
print("list1[2]: ",list1[2])
print("list1[3]: ",list1[3])
print("list1[4]: ",list1[4])
print("list1[5]: ",list1[5])
print("list1[6]: ",list1[6])
print("list1[-1]: ",list1[-1])
print("list1[-2]: ",list1[-2])
print("list1[-3]: ",list1[-3])
print("list1[-4]: ",list1[-4])
print("list1[-5]: ",list1[-5])
print("list1[-6]: ",list1[-6])
print("list1[-7]: ",list1[-7])
print("list1[0:3]: ",list1[0:3])
print("list1[2:5]: ",list1[2:5])
print("list1[::2]: ",list1[::2])
print("list1[1::2]: ",list1[1::2])
print("list1[::-1]: ",list1[::-1])

list1[0] = "Sabun"
list1[3] = "True"
print("After Updation: ",list1)
list1.append("New Item")
print("After Appending: ",list1)
list1.insert(1,"Inserted Item")
print("After Inserting: ",list1)
list1.remove("True")
print("After Removing: ",list1)
popped_item = list1.pop()
print("After Popping: ",list1)
print("Popped Item: ",popped_item)
list2 = [8,2,6,9,1,6,2]
print("List2: ",list2)
combined_list = list1 + list2
print("Combined List: ",combined_list)
list1.extend(list2)
print("List1 after extending with List2: ",list1)
list1.clear()
print("List1 after clearing: ",list1)
print("Length of List1 after clearing: ",len(list1))
print("Length of List2: ",len(list2))
list2.sort()
print("Sorted List2: ",list2)
list2.reverse()
print("Reversed List2: ",list2)
print("Index of 6 in List2: ",list2.index(6))
print("Count of 2 in List2: ",list2.count(2))

print("\n---------------Tuples---------------")
print("Tuples are immutable like Strings")
tuple1 = ()
print("Empty Tuple: ",tuple1)
print("Type of Empty Tuple: ",type(tuple1))
tuple1 = (1,)
print("Single Element Tuple: ",tuple1)
print("Type of Single Element Tuple: ",type(tuple1))
tuple1 = (1,2,3,4,5)
print("Multiple Element Tuple: ",tuple1)
print("Type of Multiple Element Tuple: ",type(tuple1))
print("Length of Tuple1: ",len(tuple1))
print("tuple1[0]: ",tuple1[0])
print("tuple1[1]: ",tuple1[1])
print("tuple1[2]: ",tuple1[2])
print("tuple1[3]: ",tuple1[3])
print("tuple1[4]: ",tuple1[4])
print("tuple1[-1]: ",tuple1[-1])
print("tuple1[-2]: ",tuple1[-2])
print("tuple1[-3]: ",tuple1[-3])
print("tuple1[-4]: ",tuple1[-4])
print("tuple1[-5]: ",tuple1[-5])
print("tuple1[0:3]: ",tuple1[0:3])
print("tuple1[2:5]: ",tuple1[2:5])
print("tuple1[::2]: ",tuple1[::2])
print("tuple1[1::2]: ",tuple1[1::2])
print("tuple1[::-1]: ",tuple1[::-1])
print("Index of 3 in Tuple1: ",tuple1.index(3))
print("Count of 2 in Tuple1: ",tuple1.count(2))
# tuple1[0] = 10 # This will raise an error as tuples are immutable
tuple1 = tuple1 + (6,7,8)
print("Tuple1 after concatenation: ",tuple1)
print("Length of Tuple1 after concatenation: ",len(tuple1))
tuple2 = (9,10,11)
combined_tuple = tuple1 + tuple2
print("Combined Tuple: ",combined_tuple)
print("Length of Combined Tuple: ",len(combined_tuple))
tuple3 = tuple(range(1,21))
print("Tuple3 with range 1 to 20: ",tuple3)
print("Length of Tuple3: ",len(tuple3))
tuple4 = ("apple","banana","cherry",12,13,14,True,False,3.14)
print("Tuple4: ",tuple4)
print("Length of Tuple4: ",len(tuple4))
for item in tuple4:
    print(item," ",end="")
    print(type(item))

    for i in range(len(tuple4)):
        print("tuple4[",i,"]: ",tuple4[i])

numbers = []

for i in range(1,11):
    numbers.append(int(input("Enter number "+str(i)+": ")))

numbers.sort()
print("Sorted Numbers: ",numbers)
print("Smallest Number: ",numbers[0])
print("Largest Number: ",numbers[-1])