print("\n---------------Tuples---------------")
print("Tuples are immutable like Strings")
tuple1 = ()
print("Empty Tuple: ",tuple1)
print("Type of Empty Tuple: ",type(tuple1))
tuple1 = (1,)
print("Single Element Tuple: ",tuple1)
print("Type of Single Element Tuple: ",type(tuple1))
tuple1 = (1,2,3,4,5)
print("Multiple Element Tuple: ",tuple1)
print("Type of Multiple Element Tuple: ",type(tuple1))
print("Length of Tuple1: ",len(tuple1))
print("tuple1[0]: ",tuple1[0])
print("tuple1[1]: ",tuple1[1])
print("tuple1[2]: ",tuple1[2])
print("tuple1[3]: ",tuple1[3])
print("tuple1[4]: ",tuple1[4])
print("tuple1[-1]: ",tuple1[-1])
print("tuple1[-2]: ",tuple1[-2])
print("tuple1[-3]: ",tuple1[-3])
print("tuple1[-4]: ",tuple1[-4])
print("tuple1[-5]: ",tuple1[-5])
print("tuple1[0:3]: ",tuple1[0:3])
print("tuple1[2:5]: ",tuple1[2:5])
print("tuple1[::2]: ",tuple1[::2])
print("tuple1[1::2]: ",tuple1[1::2])
print("tuple1[::-1]: ",tuple1[::-1])
print("Index of 3 in Tuple1: ",tuple1.index(3))
print("Count of 2 in Tuple1: ",tuple1.count(2))
# tuple1[0] = 10 # This will raise an error as tuples are immutable
tuple1 = tuple1 + (6,7,8)
print("Tuple1 after concatenation: ",tuple1)
print("Length of Tuple1 after concatenation: ",len(tuple1))
tuple2 = (9,10,11)
combined_tuple = tuple1 + tuple2
print("Combined Tuple: ",combined_tuple)
print("Length of Combined Tuple: ",len(combined_tuple))
tuple3 = tuple(range(1,21))
print("Tuple3 with range 1 to 20: ",tuple3)
print("Length of Tuple3: ",len(tuple3))
tuple4 = ("apple","banana","cherry",12,13,14,True,False,3.14)
print("Tuple4: ",tuple4)
print("Length of Tuple4: ",len(tuple4))
for item in tuple4:
    print(item," ",end="")
    print(type(item))

    for i in range(len(tuple4)):
        print("tuple4[",i,"]: ",tuple4[i])
